#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "qa_program.h"
static uint8_t mem[1048576];
static uint32_t ld(unsigned a,unsigned n){if(a+n>sizeof mem||(n>1&&a%n)){fprintf(stderr,"unaligned/out of range load %u\n",a);exit(1);}uint32_t v=0;for(unsigned i=0;i<n;i++)v|=(uint32_t)mem[a+i]<<(8*i);return v;}
static void st(unsigned a,unsigned n,uint32_t v){if(a+n>sizeof mem||(n>1&&a%n)){fprintf(stderr,"unaligned/out of range store %u\n",a);exit(1);}for(unsigned i=0;i<n;i++)mem[a+i]=v>>(8*i);}
static uint64_t run(const char *input,int quiet){uint32_t r[32]={0};unsigned pc=START_PC;uint64_t count=0;r[2]=1048560;memcpy(mem+INPUT_ADDR,input,14);mem[INPUT_ADDR+14]=0;for(;;){if(pc>=sizeof prog/sizeof *prog||count>200000000){fprintf(stderr,"execution limit/pc error\n");exit(1);}const int *p=prog[pc++];unsigned op=p[0],d=p[1],s=p[2];int k=p[3];uint32_t x=r[s],v=0;count++;switch(op){case 0:r[d]=x+k;break;case 1:r[d]=(uint32_t)k<<12;break;case 2:r[d]=x+r[k];break;case 3:r[d]=x-r[k];break;case 4:r[d]=x|r[k];break;case 5:r[d]=x&r[k];break;case 6:r[d]=x<<(r[k]&31);break;case 7:r[d]=x>>(r[k]&31);break;case 8:r[d]=x<<(k&31);break;case 9:r[d]=x>>(k&31);break;case 10:r[d]=x&k;break;case 11:r[d]=ld(x+k,1);break;case 12:r[d]=ld(x+k,2);break;case 13:r[d]=ld(x+k,4);break;case 14:st(x+k,1,r[d]);break;case 15:st(x+k,4,r[d]);break;case 16:if(r[d]==x)pc=k;break;case 17:if(r[d]!=x)pc=k;break;case 18:if(r[d]<x)pc=k;break;case 19:if(r[d]>=x)pc=k;break;case 20:r[d]=pc*4;pc=k;break;case 21:v=pc*4;pc=((x+k)&~1u)/4;r[d]=v;break;case 22:if(r[17]==93){if(r[10]){fprintf(stderr,"target failed on %s\n",input);exit(1);}FILE*dump=fopen("qa-led.bin","wb");if(dump){fwrite(mem+262144,1,3500,dump);fclose(dump);}return count;}if(r[17]==4&&!quiet)fputs((char*)mem+r[10],stdout);else if(r[17]!=4){fprintf(stderr,"bad ecall\n");exit(1);}break;case 23:if((int32_t)r[d]>=(int32_t)x)pc=k;break;case 24:r[d]=x<r[k];break;case 25:r[d]=x^r[k];break;default:exit(1);}r[0]=0;}}
int main(int argc,char **argv){FILE*f=fopen("qa_data.bin","rb");if(!f)return 1;size_t loaded=fread(mem,1,sizeof mem,f);if(loaded<65536||ferror(f)){fclose(f);return 1;}fclose(f);if(argc==2&&strcmp(argv[1],"--hard")){uint64_t n=run(argv[1],0);printf("Independent interpreter instructions=%llu (not Ripes)\n",(unsigned long long)n);return 0;}if(argc==2){f=fopen("tests/hard11.txt","r");char line[64],worst[64];unsigned checked=0;uint64_t max=0;while(fgets(line,sizeof line,f)){line[14]=0;uint64_t n=run(line,1);if(n>max){max=n;strcpy(worst,line);}checked++;}fclose(f);printf("Independent RV32I interpreter: %u hard states PASS; max instructions=%llu; worst=%s\n",checked,(unsigned long long)max,worst);return 0;}return 2;}
