#define main original_main
#include "original/solver.c"
#undef main
#include "engine.h"
#include <assert.h>
#include <time.h>
static uint16_t pt[3][5040],ot[3][729];
static uint8_t dist[STATES];static uint32_t queue[STATES];
static void encode(state_t *s,uint32_t *a,uint32_t *b){uint8_t z[7];for(unsigned i=0;i<7;i++)z[s->p[i]]=i|(s->o[i]<<3);*a=z[0]|(z[1]<<8)|(z[2]<<16)|((uint32_t)z[3]<<24);*b=z[3]|(z[4]<<8)|(z[5]<<16)|((uint32_t)z[6]<<24);}
int main(int argc,char**argv){clock_t start=clock();state_t s;for(unsigned p=0;p<5040;p++){unrank_state(p*729,&s);for(unsigned f=0;f<3;f++){state_t t=quarter_turn(s,f);pt[f][p]=rank_state(&t)/729;}}for(unsigned o=0;o<729;o++){unrank_state(o,&s);for(unsigned f=0;f<3;f++){state_t t=quarter_turn(s,f);ot[f][o]=rank_state(&t)%729;}}memset(dist,255,sizeof dist);dist[0]=0;unsigned head=0,tail=1;while(head<tail){unsigned r=queue[head++],p=r/729,o=r%729;for(unsigned f=0;f<3;f++){unsigned np=p,no=o;for(unsigned t=0;t<3;t++){np=pt[f][np];no=ot[f][no];unsigned n=np*729+no;if(dist[n]==255){dist[n]=dist[r]+1;queue[tail++]=n;}}}}assert(tail==STATES);unsigned hist[12]={0};for(unsigned r=0;r<STATES;r++){assert(dist[r]<=11);hist[dist[r]]++;unrank_state(r,&s);uint32_t a,b;encode(&s,&a,&b);assert(heuristic(a,b)<=dist[r]);}puts("H1 PASS: every state's heuristic <= exact BFS distance");for(unsigned i=0;i<12;i++)printf("depth %u: %u\n",i,hist[i]);fflush(stdout);
FILE *hard=fopen("tests/hard11.txt","w");assert(hard);unsigned checked=0,worst=0;uint64_t maxnodes=0,totalnodes=0;int full=argc>1&&!strcmp(argv[1],"--full");for(unsigned r=0;r<STATES;r++){if(dist[r]==11){unrank_state(r,&s);for(unsigned i=0;i<7;i++)fputc('1'+s.p[i],hard);for(unsigned i=0;i<7;i++)fputc('1'+s.o[i],hard);fputc('\n',hard);}if(!full&&dist[r]!=11)continue;unrank_state(r,&s);uint32_t a,b;encode(&s,&a,&b);uint8_t path[11];uint64_t nodes;int n=search(a,b,path,&nodes);assert(n==dist[r]);for(int k=0;k<n;k++)s=apply_move(s,path[k]);assert(rank_state(&s)==0);checked++;totalnodes+=nodes;if(nodes>maxnodes){maxnodes=nodes;worst=r;}if(full&&checked%100000==0){printf("H3 progress %u/%u\n",checked,STATES);fflush(stdout);}}
fclose(hard);printf("%s: checked %u optimal paths; max candidates=%llu at rank=%u; total=%llu; CPU seconds=%.3f\n",full?"H3 PASS":"Hard-11 host check PASS (H3 full still required)",checked,(unsigned long long)maxnodes,worst,(unsigned long long)totalnodes,(double)(clock()-start)/CLOCKS_PER_SEC);unrank_state(worst,&s);printf("Worst candidate-count vector: ");for(unsigned i=0;i<7;i++)putchar('1'+s.p[i]);for(unsigned i=0;i<7;i++)putchar('1'+s.o[i]);puts("");return 0;}
